### ISSUE TITLE
solid

### ISSUE THREAD

**Issue by Bingquan-InSAR** [aresys-srl/sar-calibration-tool#1]
I have run “pip install .”. Can you help me to solve this problem！
![Uploading b13d2f9866512038b8205f0ead6b66a.png…]()

**Comment by rpiantanida** [comment]
Could you please reupload the image (current one cannot be opened)? or copy and paste details of the issue?

**Comment by Bingquan-InSAR** [comment]
![20220621221311](https://user-images.githubusercontent.com/38463989/174830252-f44f92d5-0a10-4b65-9f05-febf3d38862a.png)

**Comment by Bingquan-InSAR** [comment]
I have run the command “pip install .”.

**Comment by rpiantanida** [comment]
The issue seems related to an external tool used by SCT, i.e. solid.
Most probably you have to recompile this tool for your specific architecture.
Please follow the dedicated section of the documentation.

**Comment by Bingquan-InSAR** [comment]
How can i recompile this tool? Thank you.

**Comment by rpiantanida** [comment]
Here a screenshot from documentation.

![image](https://user-images.githubusercontent.com/62283175/174835409-fbaa9695-f9cb-4b0c-9655-f6a591518921.png)

**Comment by Bingquan-InSAR** [comment]
Thank you, I have solve my question.

**Comment by rpiantanida** [comment]
Perfect! Thank you for your interest in SCT! :)
