### ISSUE TITLE
Installation improvements

### ISSUE THREAD

**Issue by avalentino** [aresys-srl/sar-calibration-tool#3]
Please note that the `stcorp` channel used in `[environment.yml](https://github.com/aresys-srl/sar-calibration-tool/blob/main/environment.yml)` is no longer available. The `coda` package is now in `conda-forge`.

Moreover it would be nice to have all the dependencies properly tracked in the `setup.py` file.

Finally you are including in the source pre-built binary versions of the `solid` module.
This is not considered a good practice in general.
The description of how to generate the extension module manually is included in the documentation but it would be very nice to have it automated so that the SW can be just installed using a standard `pip` command.
Please declare the extension module in `setup.py` such that it can be automatically built during the installation with `pip`.

**Comment by dimitriskakoullis** [comment]
Can you please clarify the following error of the SET? It seems like a py file is missing (or I am doing something wrong):

Exception has occurred: ModuleNotFoundError
No module named 'sct.external.solid'
  File "/.../.../sct/analysis/setanalyser.py", line 18, in <module>
    **import sct.external.solid as solid**

ModuleNotFoundError: No module named 'sct.external.solid'

**Comment by alecotare** [comment]
Hi, please check this closed issue where the same problem was discussed

https://github.com/aresys-srl/sar-calibration-tool/issues/1

**Comment by alecotare** [comment]
Dependencies management has been updated in v1.0.2
Installation of solid has been kept as a separate step.
